### PR TITLE
Update to golang 1.9.2

### PR DESCRIPTION
**Pull request by vdemeester**
/cc @dnephin @thaJeztah 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Note that moby/moby update to Go 1.9.2 is still blocked on https://github.com/Microsoft/hcsshim/pull/144 (in case having mixed client/daemon would be a concern.

**Comment by vdemeester** [comment]
@thaJeztah yep I know, but this can be used by other projects too 👼

**Comment by thaJeztah** [comment]
Should we tag the images with their Golang version? We currently only have `:latest` https://hub.docker.com/r/dockercore/golang-cross/tags/

(Although we _do_ pin by digest in https://github.com/docker/cli, so I guess it's not a big issue)

**Comment by vdemeester** [comment]
@thaJeztah yes, I was wondering about that 👼 😛

**Comment by dnephin** [comment]
tagging by version SGTM

**Pull request merged**
