### PR TITLE
Bump default golang to 1.13.0

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

Go 1.13 is a major release of Go.

Full diff here https://github.com/golang/go/compare/go1.12.9...go1.13

All tracking issues https://github.com/golang/go/milestone/83?closed=1

### CODE REVIEW

**Comment by tao12345666333** [comment]
@thaJeztah Thanks for you point. :+1:

**Comment by thaJeztah** [comment]
Thank you!

Before merging, I'd like to build this locally, and test cross compile for macOS (to be sure the new value works 🤗)

**Comment by thaJeztah** [comment]
Hm... wondering if this is gonna work; looking at https://github.com/docker/golang-cross/blob/03f58e718a7f632b8c401e39179fa258b7a1261c/osx-cross.sh#L23

(which corresponds with MacOS 10.10) 🤔

**Comment by thaJeztah** [comment]
ok; https://formulae.brew.sh/formula/libtool looks like the codename should be `el_capitan` (I tried it without an underscore initially.

Gonna try it locally first

**Comment by thaJeztah** [comment]
Tried building with `el_capitan` as codename, and looks like there's issues;

<details>

```
 => ERROR [5/5] RUN     /tmp/osx-cross.sh                                                                                                                                                                                      192.4s 
------                                                                                                                                                                                                                                
 > [5/5] RUN     /tmp/osx-cross.sh:                                                                                                                                                                                                   
#9 0.330 Reading package lists...                                                                                                                                                                                                     
#9 0.992 Building dependency tree...                                                                                                                                                                                                  
#9 1.146 Reading state information...                                                                                                                                                                                                 
#9 1.389 xz-utils is already the newest version (5.2.4-1).                                                                                                                                                                            
#9 1.389 xz-utils set to manually installed.
#9 1.389 The following additional packages will be installed:
#9 1.389   binfmt-support clang-7 lib32gcc1 lib32stdc++6 libc6-i386
#9 1.390   libclang-common-7-dev libclang1-7 libgc1c2 libllvm7 libmagic-mgc libmagic1
#9 1.391   libobjc-8-dev libobjc4 libpipeline1 llvm-7 llvm-7-runtime llvm-runtime
#9 1.392 Suggested packages:
#9 1.392   clang-7-doc llvm-7-doc ed diffutils-doc
#9 1.392 Recommended packages:
#9 1.392   llvm-7-dev libomp-7-dev
#9 1.557 The following NEW packages will be installed:
#9 1.557   binfmt-support clang clang-7 file lib32gcc1 lib32stdc++6 libc6-i386
#9 1.558   libclang-common-7-dev libclang1-7 libgc1c2 libllvm7 libmagic-mgc libmagic1
#9 1.559   libobjc-8-dev libobjc4 libpipeline1 llvm llvm-7 llvm-7-runtime llvm-runtime
#9 1.560   patch
#9 1.619 0 upgraded, 21 newly installed, 0 to remove and 2 not upgraded.
#9 1.619 Need to get 39.3 MB of archives.
#9 1.619 After this operation, 207 MB of additional disk space will be used.
#9 1.619 Get:1 http://security.debian.org/debian-security buster/updates/main amd64 patch amd64 2.7.6-3+deb10u1 [126 kB]
#9 1.623 Get:2 http://deb.debian.org/debian buster/main amd64 libmagic-mgc amd64 1:5.35-4 [242 kB]
#9 1.689 Get:3 http://deb.debian.org/debian buster/main amd64 libmagic1 amd64 1:5.35-4 [117 kB]
#9 1.711 Get:4 http://deb.debian.org/debian buster/main amd64 file amd64 1:5.35-4 [66.3 kB]
#9 1.723 Get:5 http://deb.debian.org/debian buster/main amd64 libpipeline1 amd64 1.5.1-2 [31.2 kB]
#9 1.729 Get:6 http://deb.debian.org/debian buster/main amd64 binfmt-support amd64 2.2.0-2 [70.0 kB]
#9 1.741 Get:7 http://deb.debian.org/debian buster/main amd64 libllvm7 amd64 1:7.0.1-8 [13.0 MB]
#9 3.849 Get:8 http://deb.debian.org/debian buster/main amd64 libgc1c2 amd64 1:7.6.4-0.4 [224 kB]
#9 3.876 Get:9 http://deb.debian.org/debian buster/main amd64 libobjc4 amd64 8.3.0-6 [50.3 kB]
#9 3.883 Get:10 http://deb.debian.org/debian buster/main amd64 libobjc-8-dev amd64 8.3.0-6 [226 kB]
#9 3.920 Get:11 http://deb.debian.org/debian buster/main amd64 libc6-i386 amd64 2.28-10 [2872 kB]
#9 4.381 Get:12 http://deb.debian.org/debian buster/main amd64 lib32gcc1 amd64 1:8.3.0-6 [47.9 kB]
#9 4.387 Get:13 http://deb.debian.org/debian buster/main amd64 lib32stdc++6 amd64 8.3.0-6 [407 kB]
#9 4.453 Get:14 http://deb.debian.org/debian buster/main amd64 libclang-common-7-dev amd64 1:7.0.1-8 [3154 kB]
#9 4.963 Get:15 http://deb.debian.org/debian buster/main amd64 libclang1-7 amd64 1:7.0.1-8 [5993 kB]
#9 8.567 Get:16 http://deb.debian.org/debian buster/main amd64 clang-7 amd64 1:7.0.1-8 [7891 kB]
#9 9.874 Get:17 http://deb.debian.org/debian buster/main amd64 clang amd64 1:7.0-47 [7468 B]
#9 9.874 Get:18 http://deb.debian.org/debian buster/main amd64 llvm-7-runtime amd64 1:7.0.1-8 [190 kB]
#9 9.900 Get:19 http://deb.debian.org/debian buster/main amd64 llvm-runtime amd64 1:7.0-47 [7132 B]
#9 9.902 Get:20 http://deb.debian.org/debian buster/main amd64 llvm-7 amd64 1:7.0.1-8 [4553 kB]
#9 10.63 Get:21 http://deb.debian.org/debian buster/main amd64 llvm amd64 1:7.0-47 [9472 B]
#9 11.00 debconf: delaying package configuration, since apt-utils is not installed
#9 11.03 Fetched 39.3 MB in 9s (4339 kB/s)
#9 11.05 Selecting previously unselected package libmagic-mgc.
(Reading database ... 24338 files and directories currently installed.)
#9 11.07 Preparing to unpack .../00-libmagic-mgc_1%3a5.35-4_amd64.deb ...
#9 11.07 Unpacking libmagic-mgc (1:5.35-4) ...
#9 11.33 Selecting previously unselected package libmagic1:amd64.
#9 11.33 Preparing to unpack .../01-libmagic1_1%3a5.35-4_amd64.deb ...
#9 11.34 Unpacking libmagic1:amd64 (1:5.35-4) ...
#9 11.38 Selecting previously unselected package file.
#9 11.38 Preparing to unpack .../02-file_1%3a5.35-4_amd64.deb ...
#9 11.39 Unpacking file (1:5.35-4) ...
#9 11.43 Selecting previously unselected package libpipeline1:amd64.
#9 11.43 Preparing to unpack .../03-libpipeline1_1.5.1-2_amd64.deb ...
#9 11.44 Unpacking libpipeline1:amd64 (1.5.1-2) ...
#9 11.48 Selecting previously unselected package binfmt-support.
#9 11.48 Preparing to unpack .../04-binfmt-support_2.2.0-2_amd64.deb ...
#9 11.50 Unpacking binfmt-support (2.2.0-2) ...
#9 11.55 Selecting previously unselected package libllvm7:amd64.
#9 11.55 Preparing to unpack .../05-libllvm7_1%3a7.0.1-8_amd64.deb ...
#9 11.55 Unpacking libllvm7:amd64 (1:7.0.1-8) ...
#9 15.38 Selecting previously unselected package libgc1c2:amd64.
#9 15.39 Preparing to unpack .../06-libgc1c2_1%3a7.6.4-0.4_amd64.deb ...
#9 15.39 Unpacking libgc1c2:amd64 (1:7.6.4-0.4) ...
#9 15.46 Selecting previously unselected package libobjc4:amd64.
#9 15.46 Preparing to unpack .../07-libobjc4_8.3.0-6_amd64.deb ...
#9 15.46 Unpacking libobjc4:amd64 (8.3.0-6) ...
#9 15.49 Selecting previously unselected package libobjc-8-dev:amd64.
#9 15.50 Preparing to unpack .../08-libobjc-8-dev_8.3.0-6_amd64.deb ...
#9 15.50 Unpacking libobjc-8-dev:amd64 (8.3.0-6) ...
#9 15.66 Selecting previously unselected package libc6-i386.
#9 15.67 Preparing to unpack .../09-libc6-i386_2.28-10_amd64.deb ...
#9 15.67 Unpacking libc6-i386 (2.28-10) ...
#9 16.38 Selecting previously unselected package lib32gcc1.
#9 16.38 Preparing to unpack .../10-lib32gcc1_1%3a8.3.0-6_amd64.deb ...
#9 16.38 Unpacking lib32gcc1 (1:8.3.0-6) ...
#9 16.43 Selecting previously unselected package lib32stdc++6.
#9 16.44 Preparing to unpack .../11-lib32stdc++6_8.3.0-6_amd64.deb ...
#9 16.44 Unpacking lib32stdc++6 (8.3.0-6) ...
#9 16.55 Selecting previously unselected package libclang-common-7-dev.
#9 16.56 Preparing to unpack .../12-libclang-common-7-dev_1%3a7.0.1-8_amd64.deb ...
#9 16.56 Unpacking libclang-common-7-dev (1:7.0.1-8) ...
#9 18.56 Selecting previously unselected package libclang1-7.
#9 18.57 Preparing to unpack .../13-libclang1-7_1%3a7.0.1-8_amd64.deb ...
#9 18.57 Unpacking libclang1-7 (1:7.0.1-8) ...
#9 20.07 Selecting previously unselected package clang-7.
#9 20.07 Preparing to unpack .../14-clang-7_1%3a7.0.1-8_amd64.deb ...
#9 20.08 Unpacking clang-7 (1:7.0.1-8) ...
#9 22.18 Selecting previously unselected package clang.
#9 22.18 Preparing to unpack .../15-clang_1%3a7.0-47_amd64.deb ...
#9 22.18 Unpacking clang (1:7.0-47) ...
#9 22.21 Selecting previously unselected package llvm-7-runtime.
#9 22.22 Preparing to unpack .../16-llvm-7-runtime_1%3a7.0.1-8_amd64.deb ...
#9 22.22 Unpacking llvm-7-runtime (1:7.0.1-8) ...
#9 22.30 Selecting previously unselected package llvm-runtime.
#9 22.30 Preparing to unpack .../17-llvm-runtime_1%3a7.0-47_amd64.deb ...
#9 22.31 Unpacking llvm-runtime (1:7.0-47) ...
#9 22.33 Selecting previously unselected package llvm-7.
#9 22.34 Preparing to unpack .../18-llvm-7_1%3a7.0.1-8_amd64.deb ...
#9 22.34 Unpacking llvm-7 (1:7.0.1-8) ...
#9 23.52 Selecting previously unselected package llvm.
#9 23.53 Preparing to unpack .../19-llvm_1%3a7.0-47_amd64.deb ...
#9 23.54 Unpacking llvm (1:7.0-47) ...
#9 23.59 Selecting previously unselected package patch.
#9 23.60 Preparing to unpack .../20-patch_2.7.6-3+deb10u1_amd64.deb ...
#9 23.60 Unpacking patch (2.7.6-3+deb10u1) ...
#9 23.70 Setting up libpipeline1:amd64 (1.5.1-2) ...
#9 23.72 Setting up libmagic-mgc (1:5.35-4) ...
#9 23.74 Setting up libgc1c2:amd64 (1:7.6.4-0.4) ...
#9 23.75 Setting up libmagic1:amd64 (1:5.35-4) ...
#9 23.78 Setting up libobjc4:amd64 (8.3.0-6) ...
#9 23.79 Setting up file (1:5.35-4) ...
#9 23.80 Setting up libobjc-8-dev:amd64 (8.3.0-6) ...
#9 23.82 Setting up patch (2.7.6-3+deb10u1) ...
#9 23.84 Setting up binfmt-support (2.2.0-2) ...
#9 24.07 invoke-rc.d: could not determine current runlevel
#9 24.08 invoke-rc.d: policy-rc.d denied execution of start.
#9 24.08 Setting up libc6-i386 (2.28-10) ...
#9 24.09 Setting up libllvm7:amd64 (1:7.0.1-8) ...
#9 24.10 Setting up libclang1-7 (1:7.0.1-8) ...
#9 24.11 Setting up llvm-7-runtime (1:7.0.1-8) ...
#9 24.12 Setting up llvm-7 (1:7.0.1-8) ...
#9 24.13 Setting up lib32gcc1 (1:8.3.0-6) ...
#9 24.14 Setting up lib32stdc++6 (8.3.0-6) ...
#9 24.15 Setting up llvm-runtime (1:7.0-47) ...
#9 24.16 Setting up llvm (1:7.0-47) ...
#9 24.17 Setting up libclang-common-7-dev (1:7.0.1-8) ...
#9 24.18 Setting up clang-7 (1:7.0.1-8) ...
#9 24.19 Setting up clang (1:7.0-47) ...
#9 24.21 Processing triggers for libc-bin (2.28-10) ...
#9 24.28 
#9 24.28 real	0m23.961s
#9 24.28 user	0m6.077s
#9 24.28 sys	0m3.365s
#9 24.28 Cloning osxcross
#9 24.28 Cloning into '/osxcross'...
#9 31.26 
#9 31.26 real	0m6.981s
#9 31.26 user	0m0.691s
#9 31.26 sys	0m0.911s
#9 31.28 Downloading OSX SDK
#9 69.33 
#9 69.33 real	0m38.046s
#9 69.33 user	0m0.445s
#9 69.33 sys	0m0.840s
#9 69.47 /osxcross/tarballs/MacOSX10.10.sdk.tar.xz: OK
#9 69.47 Building osxcross
#9 83.92 ar: `u' modifier ignored since `D' is the default (see `U')
#9 99.92 /usr/bin/ld: strip.o: in function `strip_file':
#9 99.92 strip.c:(.text+0x13f5): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
#9 100.2 /usr/bin/ld: bitcode_strip-bitcode_strip.o: in function `strip_bitcode_segment':
#9 100.2 bitcode_strip.c:(.text+0x92c): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
#9 105.9 ar: `u' modifier ignored since `D' is the default (see `U')
#9 109.2 /usr/bin/ld: otool-print_bitcode.o: in function `print_bitcode_section':
#9 109.2 print_bitcode.c:(.text+0x399): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
#9 109.8 ar: `u' modifier ignored since `D' is the default (see `U')
#9 111.1 ar: `u' modifier ignored since `D' is the default (see `U')
#9 112.7 In file included from macho_dylib_file.cpp:37:
#9 112.7 In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/memory:80:
#9 112.7 /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:81:2: warning: delete called on non-final 'ld::Bitcode' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
#9 112.7         delete __ptr;
#9 112.7         ^
#9 112.7 /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:274:4: note: in instantiation of member function 'std::default_delete<ld::Bitcode>::operator()' requested here
#9 112.7           get_deleter()(__ptr);
#9 112.7           ^
#9 112.7 ./generic_dylib_file.hpp:123:7: note: in instantiation of member function 'std::unique_ptr<ld::Bitcode, std::default_delete<ld::Bitcode> >::~unique_ptr' requested here
#9 112.7 class File : public ld::dylib::File
#9 112.7       ^
#9 112.7 macho_dylib_file.cpp:556:14: note: in instantiation of member function 'mach_o::dylib::File<x86_64>::File' requested here
#9 112.7                 return new File<A>(fileContent, fileLength, path, mTime, ordinal, opts.flatNamespace(),
#9 112.7                            ^
#9 112.7 macho_dylib_file.cpp:794:28: note: in instantiation of member function 'mach_o::dylib::Parser<x86_64>::parse' requested here
#9 112.7                                 return Parser<x86_64>::parse(fileContent, fileLength, path, modTime, ordinal, opts, indirectDylib);
#9 112.7                                                        ^
#9 112.9 In file included from macho_relocatable_file.cpp:46:
#9 112.9 In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/memory:80:
#9 112.9 /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:81:2: warning: delete called on non-final 'ld::Bitcode' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
#9 112.9         delete __ptr;
#9 112.9         ^
#9 112.9 /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:274:4: note: in instantiation of member function 'std::default_delete<ld::Bitcode>::operator()' requested here
#9 112.9           get_deleter()(__ptr);
#9 112.9           ^
#9 112.9 macho_relocatable_file.cpp:76:12: note: in instantiation of member function 'std::unique_ptr<ld::Bitcode, std::default_delete<ld::Bitcode> >::~unique_ptr' requested here
#9 112.9                                                                                         File(const char* p, time_t mTime, const uint8_t* content, ld::File::Ordinal ord) :
#9 112.9                                                                                         ^
#9 112.9 macho_relocatable_file.cpp:1721:14: note: in instantiation of member function 'mach_o::relocatable::File<x86_64>::File' requested here
#9 112.9         _file = new File<A>(_path, _modTime, _fileContent, _ordinal);
#9 112.9                     ^
#9 112.9 macho_relocatable_file.cpp:992:26: note: in instantiation of member function 'mach_o::relocatable::Parser<x86_64>::parse' requested here
#9 112.9                                                                                                                                 return p.parse(opts);
#9 112.9                                                                                                                                          ^
#9 112.9 macho_relocatable_file.cpp:7761:49: note: in instantiation of member function 'mach_o::relocatable::Parser<x86_64>::parse' requested here
#9 112.9                                 return mach_o::relocatable::Parser<x86_64>::parse(fileContent, fileLength, path, modTime, ordinal, opts);
#9 112.9                                                                             ^
#9 114.2 In file included from textstub_dylib_file.cpp:30:
#9 114.2 In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/memory:80:
#9 114.2 /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:81:2: warning: delete called on non-final 'ld::Bitcode' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
#9 114.2         delete __ptr;
#9 114.2         ^
#9 114.2 /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:274:4: note: in instantiation of member function 'std::default_delete<ld::Bitcode>::operator()' requested here
#9 114.2           get_deleter()(__ptr);
#9 114.2           ^
#9 114.2 ./generic_dylib_file.hpp:123:7: note: in instantiation of member function 'std::unique_ptr<ld::Bitcode, std::default_delete<ld::Bitcode> >::~unique_ptr' requested here
#9 114.2 class File : public ld::dylib::File
#9 114.2       ^
#9 114.2 textstub_dylib_file.cpp:684:14: note: in instantiation of member function 'textstub::dylib::File<x86_64>::File' requested here
#9 114.2                 return new File<A>(fileContent, fileLength, path, mTime, ordinal,
#9 114.2                            ^
#9 114.2 textstub_dylib_file.cpp:725:28: note: in instantiation of member function 'textstub::dylib::Parser<x86_64>::parse' requested here
#9 114.2                                 return Parser<x86_64>::parse(fileContent, fileLength, path, modTime, ordinal, opts, indirectDylib);
#9 114.2                                                        ^
#9 115.4 1 warning generated.
#9 117.2 1 warning generated.
#9 122.2 1 warning generated.
#9 122.5 ar: `u' modifier ignored since `D' is the default (see `U')
#9 130.4 ar: `u' modifier ignored since `D' is the default (see `U')
------
executor failed running [/bin/sh -c /tmp/osx-cross.sh]: exit code: 1
```

</details>

**Comment by tao12345666333** [comment]
I haven't used macOS for a long time, sorry, I ignored this message.

I just tested the build on another mac OS 1.13 and got a similar error to you.

And I try to update `OSX_SDK=MacOSX10.10.sdk` for test. :crying_cat_face:

**Comment by thaJeztah** [comment]
Tried building with `golang:1.12.9-buster` and get the same error; now trying again with setting the MacOs version back (but it might be related to the bump from stretch to buster)

Having dinner in a bit, so might be back later 😂

**Comment by tao12345666333** [comment]
When I build using `golang:1.12.9` from master branch. I get the same error, but It can be built successfully.

```
In file included from macho_relocatable_file.cpp:46:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/memory:80:
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:81:2: warning: delete called on non-final 'ld::Bitcode' that has virtual functions but non-virtual destructor [-Wdelete-non-virtua
l-dtor]
        delete __ptr;
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:274:4: note: in instantiation of member function 'std::default_delete<ld::Bitcode>::operator()' requested here
          get_deleter()(__ptr);
          ^
macho_relocatable_file.cpp:76:12: note: in instantiation of member function 'std::unique_ptr<ld::Bitcode, std::default_delete<ld::Bitcode> >::~unique_ptr' requested here
                                                                                        File(const char* p, time_t mTime, const uint8_t* content, ld::File::Ordinal ord) :
                                                                                        ^
macho_relocatable_file.cpp:1721:14: note: in instantiation of member function 'mach_o::relocatable::File<x86_64>::File' requested here
        _file = new File<A>(_path, _modTime, _fileContent, _ordinal);
                    ^
macho_relocatable_file.cpp:992:26: note: in instantiation of member function 'mach_o::relocatable::Parser<x86_64>::parse' requested here
                                                                                                                                return p.parse(opts);
                                                                                                                                         ^
macho_relocatable_file.cpp:7761:49: note: in instantiation of member function 'mach_o::relocatable::Parser<x86_64>::parse' requested here
                                return mach_o::relocatable::Parser<x86_64>::parse(fileContent, fileLength, path, modTime, ordinal, opts);
                                                                            ^
In file included from textstub_dylib_file.cpp:30:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/memory:80:
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:81:2: warning: delete called on non-final 'ld::Bitcode' that has virtual functions but non-virtual destructor [-Wdelete-non-virtua
l-dtor]
        delete __ptr;
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:274:4: note: in instantiation of member function 'std::default_delete<ld::Bitcode>::operator()' requested here
          get_deleter()(__ptr);
          ^
./generic_dylib_file.hpp:123:7: note: in instantiation of member function 'std::unique_ptr<ld::Bitcode, std::default_delete<ld::Bitcode> >::~unique_ptr' requested here
class File : public ld::dylib::File
      ^
textstub_dylib_file.cpp:684:14: note: in instantiation of member function 'textstub::dylib::File<x86_64>::File' requested here
                return new File<A>(fileContent, fileLength, path, mTime, ordinal,
                           ^
textstub_dylib_file.cpp:725:28: note: in instantiation of member function 'textstub::dylib::Parser<x86_64>::parse' requested here
                                return Parser<x86_64>::parse(fileContent, fileLength, path, modTime, ordinal, opts, indirectDylib);
                                                       ^
1 warning generated.
1 warning generated.
1 warning generated.
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
Installing libtool from brew
Removing intermediate container 0c78645cae55
 ---> 79783c85495e
Step 7/7 : ENV     PATH /osxcross/target/bin:$PATH
 ---> Running in 666403bfc351
Removing intermediate container 666403bfc351
 ---> 666e0df4b8a9
Successfully built 666e0df4b8a9
Successfully tagged golang-cross:latest

```

**Comment by thaJeztah** [comment]
Oh, forgot to post; yes, current master shows warnings, but doesn't _fail_ (not sure if it's just different in reporting warnings as a non-zero exit code?)

had a script running to check what combinations built and what not, and looks that it's the `10.10` -> `10.11` change that's the trouble one. Wondering if we need a new version of the package at `s3.dockerproject.org`

Result             | Base Image               | OSX_VERSION_MIN | OSX_CODENAME
-------------------|--------------------------|-----------------|---------------
:white_check_mark: | `golang:1.12.9-stretch`  | 10.10           | yosemite
:white_check_mark: | `golang:1.12.9-stretch`  | 10.10           | el_capitan
:x:                | `golang:1.12.9-stretch`  | 10.11           | el_capitan
:white_check_mark: | `golang:1.12.9-buster`   | 10.10           | yosemite
:white_check_mark: | `golang:1.12.9-buster`   | 10.10           | el_capitan
:x:                | `golang:1.12.9-buster`   | 10.11           | el_capitan
:white_check_mark: | `golang:1.13.0-buster`   | 10.10           | yosemite
:white_check_mark: | `golang:1.13.0-buster`   | 10.10           | el_capitan
:x:                | `golang:1.13.0-buster`   | 10.11           | el_capitan

**Comment by thaJeztah** [comment]
@kolyshkin IIRC you last updated that package, or did I recall incorrectly? (not sure how it was constructed)

**Comment by thaJeztah** [comment]
Actually; still trying some other things; I noticed https://github.com/tpoechtrager/osxcross.git was quite a bit behind current master; updating and testing with current master

**Comment by thaJeztah** [comment]
@ndeloof pushed my "scratch" work, and opened as a PR (for easier sharing, and so that others could comment on that); https://github.com/docker/golang-cross/pull/42

**Comment by thaJeztah** [comment]
For future reference; looks like I made the wrong assumption that the current version was still based on `stretch`, but it looks like the current version (`dockercore/golang-cross:1.12.9`) on Docker Hub has already switched to `buster`, so none of the issues we're running into should be related to the switch from debian stretch to debian buster

**Comment by ndeloof** [comment]
I get a successful build with https://github.com/ndeloof/golang-cross/tree/113fix
I had to re-create a 10.11 SDK downaloding XCode and using osxcross script. I committed in my fork for convenience, but for legal reason we can't "redistribute" this way.
I'm looking into writing a script to automate this step.

**Comment by ndeloof** [comment]
I created a Dockerfile to download XCode and build SDK
https://github.com/ndeloof/golang-cross/blob/113fix/SDK.Dockerfile
not fully tested as XCode takes ages to download with my Internet connexion

**Comment by tao12345666333** [comment]
Replaced by #45 . 

Thanks for @ndeloof 's SDK.

**Pull request closed without merging**
