### PR TITLE
Bump Golang 1.11.1

### PR DESCRIPTION
**Pull request by thaJeztah**
go1.11.1 (released 2018/10/01) includes fixes to the compiler,
documentation, go command, runtime, and the crypto/x509, encoding/json,
go/types, net, net/http, and reflect packages.

See the Go 1.11.1 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.11.1

### CODE REVIEW

**Comment by thaJeztah** [comment]
/cc @vdemeester @dnephin 

Bumping to Go 1.11.1, although I see that https://github.com/docker/cli/pull/1316 was still open; perhaps  Go 1.11.1 fixes that 🤔

**Comment by thaJeztah** [comment]
hm.. looking at that one again; probably not a golang issue. Wondering if the Go image changed to a different base-image, causing things to be missing.

**Comment by thaJeztah** [comment]
Perhaps we need to fix the osx-cross stuff first; see https://github.com/docker/cli/pull/1316#issuecomment-426428573

**Comment by kolyshkin** [comment]
LGTM

**Pull request merged**
